version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "8000:8000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "3000:3000"
    # apache2:
    #     restart: always
    #     build:
    #         context: ./apache2
    #     ports:
    #         - "3000:3000"